name: Build

on: [pull_request]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Env Files
        run: |
          cp .docker/php.env.development .docker/php.env
          cp .docker/mysql.env.development .docker/mysql.env
      - name: Pull images
        run: docker-compose pull
      - name: Build
        run: docker-compose build --build-arg UID=$(id -u) --build-arg ENV=dev
      - name: Start
        run: docker-compose up -d
      - name: Check CakePHP Welcome Page
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 10
          max_attempts: 10
          command: curl -f -v -o /dev/null http://localhost:8080
      - name: Check NGINX Files
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 10
          max_attempts: 5
          command: curl -f -v -o /dev/null http://localhost:8080/css/home.css
