name: Build

on: [pull_request]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Env Files
        run: |
          cp .docker/php.env.development .docker/php.env
          cp .docker/mysql.env.development .docker/mysql.env
      - name: Pull images
        run: docker-compose pull
      - name: Build
        run: docker-compose build --build-arg UID=$(id -u) --build-arg ENV=dev
      - name: Start
        run: docker-compose up -d --wait
      - name: Check CakePHP Welcome Page
        run: curl -f -v -o /dev/null http://localhost:8080 --retry 10 --retry-delay 10
      - name: Check NGINX Files
        run: curl -f -v -o /dev/null http://localhost:8080/css/home.css --retry 10 --retry-delay 10
